name: todays_kanji
description: An App that will deliver you a new random japanese Kanji to learn every day, together with pronunciation, and usage examples.

publish_to: 'none'

version: 1.1.7+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.8
  unofficial_jisho_api: ^1.1.0
  url_launcher: ^5.5.0
  provider: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter:
  uses-material-design: true
  fonts:
    - family:  KanjiIcons
      fonts:
        - asset: fonts/KanjiIcons.ttf
    - family: Meiryo
      fonts:
        - asset: fonts/Meiryo.ttc

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"